pub mod action;
pub mod action_registry;
mod scroll_down;
mod scroll_up;
mod scroll_left;
mod scroll_right;
mod cursor_down;
mod cursor_up;
mod cursor_left;
mod cursor_right;
mod quit;
mod shift_down;
mod shift_up;
mod shift_left;
mod shift_right;
mod pgdown;
mod pgup;
mod line_start;
mod line_end;
mod file_start;
mod file_end;
mod select_all;
mod copy;
